### ISSUE TITLE
sd card error 

### ISSUE THREAD

**Issue by icelon** [david-sawatzke/s32duino#1]
In file included from /opt/arduino-1.8.5/hardware/s32duino-master/s32duino/libraries/SD/src/Sd2Card.h:25:0,
                 from /opt/arduino-1.8.5/hardware/s32duino-master/s32duino/libraries/SD/src/SDStm.h:20,
                 from /opt/arduino-1.8.5/hardware/s32duino-master/s32duino/libraries/SD/examples/CardInfo/CardInfo.ino:12:
/opt/arduino-1.8.5/hardware/s32duino-master/s32duino/libraries/SD/src/bsp_sd.h:47:21: fatal error: sd_conf.h: No such file or directory
 #include "sd_conf.h"
                     ^
compilation terminated.
exit status 1
Error compilando para la tarjeta STM32F030F4.

**Comment by david-sawatzke** [comment]
Sorry, I haven't ported the library yet. You can see that it's not listed in the "Working libraries" section in the README.
