### ISSUE TITLE
boot loader

### ISSUE THREAD

**Issue by icelon** [david-sawatzke/s32duino#2]
Could you post the bootloader ??? and squematic like using ???

**Comment by icelon** [comment]
IceLon @icelon 13:03
sorry, don't understand ?? not supp0rt for stm32f0 ?

mubes @mubes 13:04
@icelon What are you trying to do?

UweBonnes @UweBonnes 13:04
Well BMP supports F0, but making a F0 a BMP needs sipport.

IceLon @icelon 13:08
I try to prepare a stm32f030f4p6 to burn a loader for proyect https://github.com/david-sawatzke/s32duino

UweBonnes @UweBonnes 13:09
tm32f030f4 with 16 kByte flash is far too small for BMP.

IceLon @icelon 13:10
umm I just need 4k and 256k for project

mubes @mubes 13:11
@UweBonnes Just tried a 'real' BMP and got 15KBytes/sec, so some way to go yet for speed parity, but I'm happy with 5KBytes/sec with minimal code changes! Someone who wants to use a dev board for 'real' use can always enhance the stuff themselves  There's loads of headroom for improvement, but this gets me where I want to go for now. Kudos.
@icelon You need to create a debug dongle for your target. Those are two separate things.
The code you linked to is a Arduino library thing....the BMP doesn't care what you load onto the target. but the BMP itself is a completely separate board.

IceLon @icelon 13:14
umm need BMP all 16k ?

mubes @mubes 13:19
BMP takes something like 80k in its current form, but it's doing a lot more than a simple loader. There is a loader for it which is 2Kish, but I think you need to start with simpler stuff first. You need to look at ST AN2606 for more information about the embedded bootloader thats already in the 030, and Pg. 44 of the Reference Manual (I looked it up, 'cos I'm in a good mood after Uwe helped me get my stuff going and it's still lunchtime here!)
@UweBonnes whats the speedup stuff you're playing with? Now there's a BMP running on a host with plenty of memory I can do things like version caching etc too (but I am not getting distracted in another direction).

UweBonnes @UweBonnes 13:22
The SWD speedup is only removing function calls.

IceLon @icelon 13:27
ok tanks ...

**Comment by david-sawatzke** [comment]
You need a separate BMP to flash the code on the chip, no bootloader is used. You could get it by just buying it or acquiring a st link, from a Nucleo Board for example, and reflashing it.

To use the STM32F030F4 just power it with 3.3V and connect it to the BMP with the SWD pins. You can find the pinout of the chip in the datasheet

**Comment by icelon** [comment]
then once the program is compiled, I just have to dump it with the stlink and it works?

**Comment by icelon** [comment]
like pcb https://raw.githubusercontent.com/flabbergast/eagle/master/breakout_STM32F030F4P6/breakout_STM32F030F4P6.png

**Comment by mubes** [comment]
You can flash F030 over UART, following ST AN2606 (Specifically Chapter 
5 or 6 depending on your chip). If you want to be able to step through 
your program, look at variables etc. then you will need something like 
STLink, BMP or JLink.

**Comment by david-sawatzke** [comment]
The schematic you posted should work. If you want to use the integrated bootloader or another debugging probe, you can use the compiled .elf file (to find out where it is, enable verbose output during compilation) and flash it using some different tool. For the integrated bootloader you could try using a software like https://sourceforge.net/p/stm32flash/code/ci/master/tree/ (remember to pull the BOOT0 pin up). Just beware that I haven't thoroughly tested all of this, so you may run into bugs.
