### ISSUE TITLE
implementation of  pinmode digitalwire are implemented ?

### ISSUE THREAD

**Issue by icelon** [david-sawatzke/s32duino#3]
/opt/arduino-1.8.5/examples/02.Digital/BlinkWithoutDelay/BlinkWithoutDelay.ino: In function 'void setup()':
BlinkWithoutDelay:46: error: invalid conversion from 'int' to 'PinName' [-fpermissive]
   pinMode(ledPin, OUTPUT);
                         ^
In file included from /opt/arduino-1.8.5/hardware/s32duino/s32duino/cores/arduino/Arduino.h:72:0,
                 from sketch/BlinkWithoutDelay.ino.cpp:1:
/opt/arduino-1.8.5/hardware/s32duino/s32duino/cores/arduino/wiring_digital.h:32:13: error:   initializing argument 1 of 'void pinMode(PinName, uint32_t)' [-fpermissive]
 extern void pinMode( PinName p, uint32_t dwMode ) ;
             ^
/opt/arduino-1.8.5/examples/02.Digital/BlinkWithoutDelay/BlinkWithoutDelay.ino: In function 'void loop()':
BlinkWithoutDelay:69: error: invalid conversion from 'int' to 'PinName' [-fpermissive]
     digitalWrite(ledPin, ledState);
                                  ^
In file included from /opt/arduino-1.8.5/hardware/s32duino/s32duino/cores/arduino/Arduino.h:72:0,
                 from sketch/BlinkWithoutDelay.ino.cpp:1:
/opt/arduino-1.8.5/hardware/s32duino/s32duino/cores/arduino/wiring_digital.h:54:13: error:   initializing argument 1 of 'void digitalWrite(PinName, uint32_t)' [-fpermissive]
 extern void digitalWrite( PinName p, uint32_t dwVal ) ;
             ^
exit status 1
invalid conversion from 'int' to 'PinName' [-fpermissive]

**Comment by david-sawatzke** [comment]
As this library is just for the bare chip, pin numbers are kind of nonsensical.
You have to use PinName as detailed in the README: 
- There are no pin numbers, each Pin is named according to the datasheet, e.g. PA4, PA5
- Pins have the PinNumber type
